backend:
  name: github
  repo: zheng-yujie1122/test  # 你的 GitHub 仓库名
  branch: main

media_folder: "images/uploads"   # 图片上传目录（和你项目结构一致）
public_folder: "/images/uploads" # 前端访问路径

collections:
  - name: "article"
    label: "文章"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}