backend:
  name: github
  repo: zheng-yujie1122/test  # 你的 GitHub 仓库名
  branch: main
  auth_type: manual            # 用 token 登录
  token: "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"
 # base_url: https://decap-cms-oauth.18438098429.workers.dev 你的 Worker 域名

media_folder: "images/uploads"   # 图片上传目录（和你项目结构一致）
public_folder: "/images/uploads" # 前端访问路径

collections:
  - name: "article"
    label: "文章"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}