backend:
  name: github
  repo: zheng-yujie1122/test
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "页面内容"
    files:
      - label: "首页"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "text" }
          - { label: "图片", name: "image", widget: "image" }